SION/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import sion_profile.urls as sion_profile
import sion_login.urls as sion_login
import sion_register.urls as sion_register

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='/sion-login/', permanent=True), name='root'),
    url(r'^sion-login/',include(sion_login,namespace='sion-login')),
    url(r'^sion-profile/', include(sion_profile, namespace='sion-profile')),
    url(r'^sion-register/',include(sion_register,namespace='sion-register')),
]

sion_login/urls.py
from django.conf.urls import url
from .views import index #pilihrole
from .custom_auth import auth_login, auth_logout
#from .sign_up import registration

urlpatterns = [
    url(r'^$',index,name='index'),
    url(r'^custom_auth/login/$',auth_login,name='auth_login'),
    url(r'^custom_auth/logout/$',auth_logout,name='auth_logout'),
   # url(r'^$',pilihrole,name='pilihrole'),
  #  url(r'^sign_up/registration/$',registration,name='registration'),
   # url(r'^profile/$', profile, name='profile'),
]

sion_profile/urls.py
from django.conf.urls import url
from .views import index, profile

urlpatterns = [
    url(r'^$',index,name='index'),
    url(r'^profile/$',profile,name='profile'),
]

sion_profile/models.py
from django.db import models

# Create your models here.

sion_profile/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from sion_login.db_helper import DatabaseConnection

response = {}
def index(request):
	if 'email' in request.session:
		response['login'] = True
		return HttpResponseRedirect(reverse('sion-profile:profile'))

	else:
		response['login'] = False
		return HttpResponseRedirect(reverse('sion-login:index'))

def profile(request):
	if 'email' not in request.session.keys():
		return HttpResponseRedirect(reverse('sion-login:index'))

	conn = DatabaseConnection()
	conn.cursor.execute("select email, nama, alamat_lengkap from sion.user where email='"+request.session['email']+"';")
	row = conn.cursor.fetchone()
	response['email'] = row[0]
	response['nama'] = row[1]
	response['alamat'] = row[2]

	if request.session['role'] == 'donatur':
		conn.cursor.execute("select saldo from sion.donatur where email ='"+request.session['email']+"';")
		row = conn.cursor.fetchone()
		response['saldo'] = row[0]
		html = 'ProfileDonatur.html'

	elif request.session['role'] == 'sponsor':
		conn.cursor.execute("select logo_sponsor from sion.sponsor where email ='"+request.session['email']+"';")
		row = conn.cursor.fetchone()
		response['logo_sponsor'] = row[0]
		html = 'ProfileSponsor.html'

	elif request.session['role'] == 'relawan':
		conn.cursor.execute("select no_hp, tanggal_lahir from sion.relawan where email ='"+request.session['email']+"';")
		row = conn.cursor.fetchone()
		response['no_hp'] = row[0]
		response['tanggal_lahir'] = row[1]

		keahlian = []
		conn.cursor.execute("select keahlian from keahlian_relawan where email = '"+request.session['email']+"';")
		
		for row in conn.cursor.fetchall():
			keahlian.append(row[0])
		response['keahlian_dict'] = keahlian
		
		html = 'ProfileRelawan.html'

	elif request.session['role'] == 'pengurus_organisasi':
		conn.cursor.execute("select organisasi from sion.pengurus_organisasi where email ='"+request.session['email']+"';")
		row = conn.cursor.fetchone()
		response['organisasi'] = row[0]
		html = 'ProfilePengurusOrganisasi.html'

	return render(request, html, response)

sion_profile/templates/ProfileDonatur.html
<!DOCTYPE html>
<html>
<head>
	<title>Profile Donatur</title>
	<style>
		ul {
			list-style-type: none;
			margin: 0;
			padding: 0;
			overflow: hidden;
			background-color: #333;
		}

		li {
			float: left;
		}

		li a, .dropbtn {
			display: inline-block;
			color: white;
			text-align: center;
			padding: 14px 16px;
			text-decoration: none;
		}

		li a:hover, .dropdown:hover .dropbtn {
			
		}

		li.dropdown {
			
		}

		.dropdown-content {
			display: none;
			position: absolute;
			background-color: #f9f9f9;
			min-width: 160px;
			box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
			z-index: 1;
		}

		.dropdown-content a {
			color: black;
			padding: 12px 16px;
			text-decoration: none;
			display: block;
			text-align: left;
		}

		.dropdown-content a:hover {
			background-color: #f1f1f1
		}

		.dropdown:hover .dropdown-content {
			display: block;
		}
		.container {
			width: 50%;
		}

		.key {
			font-size: 30px ;
			text-align: left;
			margin: 0;
		}

		.value {
			font-size: 30px ;
			margin: 0;
			text-align: left;
		}

		.mainContainer {
		    background: #005c99; /* For browsers that do not support gradients */
		    background: linear-gradient(#005c99,#ccebff); /* Standard syntax (must be last) */

		    background-repeat: no-repeat;
		    background-size: cover;
		    background-attachment: fixed;
		    font-family: Trebuchet MS
		}

		#logout {
			position: absolute;
    		right: 50px;
    		margin-top: 10px;
			background-color: #d11919;
			padding: 5px;
			border-radius: 20%;
		}
	</style>
</head>
<body class = "mainContainer">
	<ul>
  		<li><a class="active" href="{% url 'sion-profile:profile' %}">Profile</a></li>
  		<li><a href="#organisasi">Organisasi</a></li>
  		<li class="dropdown">
    		<a href="javascript:void(0)" class="dropbtn">Donasi</a>
    		<div class="dropdown-content">
      			<a href="#">Kegiatan</a>
      			<a href="#">Organisasi</a>
    		</div>
  		</li>
  		<a href="{% url 'sion-login:auth_logout' %}" id="logout">Logout</a>
	</ul>
	
	
	<center><h1 style="color: white ; font-size: 60px; display: inline-block; margin-top: 50px">Profile</h1></center>

	<center>
	<div class="container" style="padding: 5px; background-color: rgb(255,255,255,0.8)">
		<h2 class="key">Nama</h2>
		<p class="value">{{ nama }}</p>
		<br>
		<h2 class="key">Email</h2>
		<p class="value">{{ email }}</p>
		<br>
		<h2 class="key">Alamat</h2>
		<p class="value">{{ alamat }}</p>
		<br>
		<h2 class="key">Saldo</h2>
		<p class="value">{{ saldo }}</p>
	</div>
	</center>
</body>
</html>

sion_profile/templates/ProfilePengurusOrganisasi.html
<!DOCTYPE html>
<html>
<head>
	<title>Profile Pengurus Organisasi</title>
	<style>
		ul {
			list-style-type: none;
			margin: 0;
			padding: 0;
			overflow: hidden;
			background-color: #333;
		}

		li {
			float: left;
		}

		li a, .dropbtn {
			display: inline-block;
			color: white;
			text-align: center;
			padding: 14px 16px;
			text-decoration: none;
		}

		li a:hover, .dropdown:hover .dropbtn {
			
		}

		li.dropdown {
			
		}

		.dropdown-content {
			display: none;
			position: absolute;
			background-color: #f9f9f9;
			min-width: 160px;
			box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
			z-index: 1;
		}

		.dropdown-content a {
			color: black;
			padding: 12px 16px;
			text-decoration: none;
			display: block;
			text-align: left;
		}

		.dropdown-content a:hover {
			background-color: #f1f1f1
		}

		.dropdown:hover .dropdown-content {
			display: block;
		}
		.container {
			width: 50%;
		}

		.key {
			font-size: 30px ;
			text-align: left;
			margin: 0;
		}

		.value {
			font-size: 30px ;
			margin: 0;
			text-align: left;
		}

		.mainContainer {
		    background: #005c99; /* For browsers that do not support gradients */
		    background: linear-gradient(#005c99,#ccebff); /* Standard syntax (must be last) */

		    background-repeat: no-repeat;
		    background-size: cover;
		    background-attachment: fixed;
		    font-family: Trebuchet MS
		}

		#logout {
			position: absolute;
    		right: 50px;
    		margin-top: 10px;
			background-color: #d11919;
			padding: 5px;
			border-radius: 20%;
		}
	</style>
</head>
<body class = "mainContainer">
	<ul>
  		<li><a class="active" href="{% url 'sion-profile:profile' %}">Profile</a></li>
  		<li><a href="#organisasi">Organisasi</a></li>
  		<li class="dropdown">
    		<a href="javascript:void(0)" class="dropbtn">Kegiatan</a>
    		<div class="dropdown-content">
      			<a href="#">Lihat</a>
      			<a href="#">Buat</a>
    		</div>
  		</li>
  		<a href="{% url 'sion-login:auth_logout' %}" id="logout">Logout</a>
	</ul>
	
	
	<center><h1 style="color: white ; font-size: 60px; display: inline-block; margin-top: 50px">Profile</h1></center>

	<center>
	<div class="container" style="padding: 5px; background-color: rgb(255,255,255,0.8)">
		<h2 class="key">Nama</h2>
		<p class="value">{{ nama }}</p>
		<br>
		<h2 class="key">Email</h2>
		<p class="value">{{ email }}</p>
		<br>
		<h2 class="key">Alamat</h2>
		<p class="value">{{ alamat }}</p>
		<br>
		<h2 class="key">Organisasi</h2>
		<p class="value">{{ organisasi }}</p>
	</div>
	</center>
</body>
</html>

sion_profile/templates/ProfileRelawan.html
<!DOCTYPE html>
<html>
<head>
	<title>Profile Relawan</title>
	<style>
		ul {
			list-style-type: none;
			margin: 0;
			padding: 0;
			overflow: hidden;
			background-color: #333;
		}

		li {
			float: left;
		}

		li a, .dropbtn {
			display: inline-block;
			color: white;
			text-align: center;
			padding: 14px 16px;
			text-decoration: none;
		}

		li a:hover, .dropdown:hover .dropbtn {
			
		}

		li.dropdown {
			
		}

		.dropdown-content {
			display: none;
			position: absolute;
			background-color: #f9f9f9;
			min-width: 160px;
			box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
			z-index: 1;
		}

		.dropdown-content a {
			color: black;
			padding: 12px 16px;
			text-decoration: none;
			display: block;
			text-align: left;
		}

		.dropdown-content a:hover {
			background-color: #f1f1f1
		}

		.dropdown:hover .dropdown-content {
			display: block;
		}
		.container {
			width: 50%;
		}

		.key {
			font-size: 30px ;
			text-align: left;
			margin: 0;
		}

		.value {
			font-size: 30px ;
			margin: 0;
			text-align: left;
		}

		@font-face {
		    font-family: Roboto;
		    src: url(static/Roboto-Light.ttf);
		}


		.mainContainer {
		    background: #12bbad; /* For browsers that do not support gradients */
		    background: linear-gradient(#12bbad,#4f70ce); /* Standard syntax (must be last) */

		    background-repeat: no-repeat;
		    background-size: cover;
		    background-attachment: fixed;
		    font-family: Roboto;
		}

		#logout {
			position: absolute;
    		right: 50px;
    		margin-top: 10px;
			background-color: #d11919;
			padding: 5px;
			border-radius: 20%;
		}
	</style>
</head>
<body class = "mainContainer">
	<ul>
  		<li><a class="active" href="{% url 'sion-profile:profile' %}">Profile</a></li>
  		<li><a href="#organisasi">Organisasi</a></li>
  		<li class="dropdown">
    		<a href="javascript:void(0)" class="dropbtn">Donasi</a>
    		<div class="dropdown-content">
      			<a href="#">Kegiatan</a>
      			<a href="#">Organisasi</a>
    		</div>
  		</li>
  		<a href="{% url 'sion-login:auth_logout' %}" id="logout">Logout</a>
	</ul>
	<center><h1 style="color: white ; font-size: 60px; display: inline-block; margin-top: 50px">Profile</h1></center>

	<center>
	<div class="container" style="padding: 5px; background-color: rgb(255,255,255,0.8)">
		<h2 class="key">Nama</h2>
		<p class="value">{{ nama }}</p>
		<br>
		<h2 class="key">Email</h2>
		<p class="value">{{ email }}</p>
		<br>
		<h2 class="key">Alamat</h2>
		<p class="value">{{ alamat }}</p>
		<br>
		<h2 class="key">No HP</h2>
		<p class="value">{{ no_hp }}</p>
		<br>
		<h2 class="key">Tanggal Lahir</h2>
		<p class="value">{{ tanggal_lahir }}</p>
		<br>
		<h2 class="key">Keahlian</h2>
		{% for keahlian in keahlian_dict %}
			<p class="value">{{ keahlian }}</p>
		{% endfor %}
	</div>
	</center>
</body>
</html>

sion_profile/templates/ProfileSponsor.html
<!DOCTYPE html>
<html>
<head>
	<title>Profile Sponsor</title>
	<style>
		ul {
			list-style-type: none;
			margin: 0;
			padding: 0;
			overflow: hidden;
			background-color: #333;
		}

		li {
			float: left;
		}

		li a {
			display: block;
			color: white;
			text-align: center;
			padding: 14px 16px;
			text-decoration: none;
		}

		li a:hover {
			background-color: #111;
		}
		tr {
			height: 60px;
		}

		td {
			font-size: 30px ;
			vertical-align: text-top;
		}

		.value {
			max-width: 400px;
		}
		.mainContainer {
		    background: #005c99; /* For browsers that do not support gradients */
		    background: linear-gradient(#005c99,#ccebff); /* Standard syntax (must be last) */

		    background-repeat: no-repeat;
		    background-size: cover;
		    background-attachment: fixed;
		    font-family: Trebuchet MS
		}	

		#logout {
			position: absolute;
    		right: 50px;
    		margin-top: 10px;
			background-color: #d11919;
			padding: 5px;
			border-radius: 20%;
		}
	</style>
</head>
<body class = "mainContainer">
	<ul>
  		<li><a class="active" href="{% url 'sion-profile:profile' %}">Profile</a></li>
  		<li><a href="#organisasi">Organisasi</a></li>
  		<li><a href="#donasi">Donasi Organisasi</a></li>
  		<a href="{% url 'sion-login:auth_logout' %}" id="logout">Logout</a>
	</ul>
	
	
	<center><h1 style="color: white ; font-size: 60px; display: inline-block; margin-top: 50px">Profile</h1></center>

	<center><img style="border-radius : 50% ; padding: 7px ; background-color: rgb(0, 92, 153, 0.6)" src="thanos.png" alt="Thanos!!" width="200" height="200"></center>

	<center><table style = "padding : 5px ; padding-top: 110px ; background-color: rgb(255,255,255,0.8) ; margin: -110px; border-radius: 1%" width="50%">
		<tr>
			<td class="key"><b>Nama Sponsor</b></td>
			<td>:</td>
			<td class="value">{{ nama }}</td>
		</tr>
		<tr>
			<td class="key"><b>Email</b></td>
			<td>:</td>
			<td class="value">{{ email }}</td>
		</tr>
		<tr>
			<td class="key"><b>Alamat</b></td>
			<td>:</td>
			<td class="value">{{ alamat }}</td>
		</tr>
	</table></center>
</body>
</html>