SION/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import sion_profile.urls as sion_profile
import sion_login.urls as sion_login
import sion_register.urls as sion_register

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='/sion-login/', permanent=True), name='root'),
    url(r'^sion-login/',include(sion_login,namespace='sion-login')),
    url(r'^sion-profile/', include(sion_profile, namespace='sion-profile')),
    url(r'^sion-register/',include(sion_register,namespace='sion-register')),
]

sion_login/urls.py
from django.conf.urls import url
from .views import index #pilihrole
from .custom_auth import auth_login, auth_logout
#from .sign_up import registration

urlpatterns = [
    url(r'^$',index,name='index'),
    url(r'^custom_auth/login/$',auth_login,name='auth_login'),
    url(r'^custom_auth/logout/$',auth_logout,name='auth_logout'),
   # url(r'^$',pilihrole,name='pilihrole'),
  #  url(r'^sign_up/registration/$',registration,name='registration'),
   # url(r'^profile/$', profile, name='profile'),
]

sion_login/models.py
from django.db import models

# Create your models here.

sion_login/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .db_helper import DatabaseConnection

# Create your views here.
response = {}

def index(request):
    if 'email' in request.session :
        print('logged in')
        response['login'] = True
        return HttpResponseRedirect(reverse('sion-profile:index'))

    else :
        print('not logged in')
        response['login'] = False
        html = 'Login.html'
        return render(request, html, response)

	#def pilihrole(request):
	#html = "PemilihanRole.html"
	#return render(request,html,response)

sion_login/templates/Login.html
{% load staticfiles %}
{% load static %}

<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- PAGE settings -->
  <link rel="icon" href="https://templates.pingendo.com/assets/Pingendo_favicon.ico">
  <title>Login SION</title>
  <meta name="description" content="Free Bootstrap 4 Pingendo Aquamarine template for restaurant and food">
  <meta name="keywords" content="Pingendo restaurant food aquamarine free template bootstrap 4">
  <!-- CSS dependencies -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="{% static 'css/aquamarine.css' %}" type="text/css">
  <!-- Script: Make my navbar transparent when the document is scrolled to top -->
  <script src="js/navbar-ontop.js"></script>
  <!-- Script: Animated entrance -->
  <script src="js/animate-in.js"></script>
</head>

<body>
<div class ="container">
	{% for message in messages %}
	<div class="alert {{ message.tags }} alert-dismissible" role="alert" id="django-messages">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close" style="margin-right: 15px;">
			<span aria-hidden="true">&times;</span>
		</button>
		{{ message }}
	</div>
	{% endfor %}
</div>

  <!-- Navbar -->
  <!-- Cover -->
  <nav class="navbar-expand-md navbar-dark bg-secondary navbar fixed-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">
        <i class="fa fa-fw fa-repeat"></i>SION</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center justify-content-end" id="navbar2SupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <i class="fa d-inline fa-lg fa-bookmark-o"></i> Bookmarks</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <i class="fa d-inline fa-lg fa-envelope-o"></i> Contacts</a>
          </li>
        </ul>
        <a href="{% url 'sion-register:index' %}" class="btn navbar-btn ml-2 text-white btn-success">Register</a>
      </div>
    </div>
  </nav>
  <div class="align-items-center d-flex cover section-aquamarine text-light py-5" style="background-image: url(&quot;assets/restaurant/cover_light.jpg&quot;);">
    <div class="container">
      <div class="row">
        <div class="col-lg-7 align-self-center text-lg-left text-center">
          <h3 class="display-4">Sistem Informasi Organisasi Nirlaba
            <br> </h3>
          <h1 class="text-dark text-justify text-capitalize bg-secondary">Daftarkan Organisasi Nirlaba Kamu Disini &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
            <br> </h1>
        </div>
        <div class="col-lg-5 p-3">
          <form class="p-4 bg-info" method="post" action="{% url 'sion-login:auth_login' %}">
            {% csrf_token %}
            <h4 class="mb-4 text-center">Login SION</h4>
            <div class="form-group">
              <label>Username</label>
              <input class="form-control" name="email" placeholder="Masukan Username Anda"> </div>
            <div class="form-group">
              <label>Password</label>
              <input type="password" class="form-control" name="password" placeholder="Masukan Password Anda"> </div>
            <button type="submit" class="btn mt-4 btn-block p-2 btn-primary">
              <i class="fa fa-user fa-fw"></i>
              <b>Sign In</b>
            </button>
          </form>
        </div>
      </div> 
    </div>
  </div>
  <!-- Intro -->
  <!-- Gallery -->
  <!-- Menu -->
  <!-- Carousel reviews -->
  <!-- Carousel venue -->
  <!-- Events -->
  <!-- Parallax section -->
  <!-- Footer -->
  <!-- JavaScript dependencies -->
  <script src="https://code.jquery.com/jquery-3.2.1.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <!-- Script: Smooth scrolling between anchors in the same page -->
  <script src="js/smooth-scroll.js"></script>
</body>

</html>