SION/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import sion_profile.urls as sion_profile
import sion_login.urls as sion_login
import sion_register.urls as sion_register

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='/sion-login/', permanent=True), name='root'),
    url(r'^sion-login/',include(sion_login,namespace='sion-login')),
    url(r'^sion-profile/', include(sion_profile, namespace='sion-profile')),
    url(r'^sion-register/',include(sion_register,namespace='sion-register')),
]

sion_register/urls.py
from django.conf.urls import url
from .views import index, form_register_organisasi, register_organisasi, form_register_relawan, form_register_sponsor, form_register_donatur

urlpatterns = [
    url(r'^$',index,name='index'),
    url(r'^form_register_relawan/$',form_register_relawan,name='form_register_relawan'),
    url(r'^form_register_donatur/$',form_register_donatur,name='form_register_donatur'),
    url(r'^form_register_sponsor/$',form_register_sponsor,name='form_register_sponsor'),
    url(r'^form_register_organisasi/$',form_register_organisasi,name='form_register_organisasi'),
    url(r'^register_organisasi/$',register_organisasi,name='register_organisasi'),
]

sion_register/models.py
from django.db import models

# Create your models here.

sion_register/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from sion_login.db_helper import DatabaseConnection
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse

response = {}

def index(request):
	return render(request, 'MilihRole.html', response)

def form_register_organisasi(request):
	return render(request, 'FormPengurusOrganisasi.html', response)

def form_register_relawan(request):
	return render(request, 'FormRegistrasiRelawan.html', response)

def form_register_donatur(request):
	return render(request, 'FormRegistrasiDonatur.html', response)

def form_register_sponsor(request):
	return render(request, 'FormRegistrasiSponsor.html', response)

@csrf_exempt
def register_organisasi(request):
    if 'login' not in request.session or not request.session['login']:
        if(request.method == 'POST'):
            nama_organisasi = request.POST["namaOrganisasiText"]
            website = request.POST["websiteText"]
            email = request.POST["emailText"]
            kecamatan = request.POST["kecamatanText"]
            kabupaten = request.POST["kabupatenText"]
            provinsi = request.POST["provinsiText"]
            kode_pos = request.POST["kodePosText"]
            additional_address = request.POST["additionalAddressText"]

            conn = DatabaseConnection()
            conn.cursor.execute("select * from sion.organisasi where email_organisasi='"+email+"'")
            select = conn.cursor.fetchone()
            if (select):
                messages.error(request, 'Login gagal, email organisasi sudah terdaftar.')
                return HttpResponseRedirect(reverse('sion-login:index'))

            pengurusCounter = 1;
            while ("emailPengurusText"+str(pengurusCounter)) in request.POST:
                conn.cursor.execute("select email from sion.user where email='"+request.POST["emailPengurusText1"]+"';")
                select = conn.cursor.fetchone()
                if (select):
                    messages.error(request, ('Email pengurus '+str(pengurusCounter)+' sudah pernah terdaftar.'))
                    return HttpResponseRedirect(reverse('sion-login:index'))

                pengurusCounter+=1
            
            conn.cursor.execute("insert into organisasi values('"+email+"','"+website+"','"+nama_organisasi+"','"+provinsi+"','"+
                kabupaten+"','"+kecamatan+"','"+additional_address+"','"+str(kode_pos)+"','sudah');")

            conn.cursor.execute("select nomor_registrasi from organisasi_terverifikasi order by nomor_registrasi desc limit 1;")
            select = conn.cursor.fetchone()
            nomor_registrasi = 1
            if (select):
                nomor_registrasi = int(select[0]) + 1
            conn.cursor.execute("insert into organisasi_terverifikasi values('"+email+"','"+str(nomor_registrasi)+"','aktif');")
            messages.info(request, "Nomor Registrasi: " + str(nomor_registrasi))

            tujuanCounter = 1
            while (("tujuanOrganisasiText"+str(tujuanCounter)) in request.POST):
                tujuan = request.POST["tujuanOrganisasiText"+str(tujuanCounter)]
                conn.cursor.execute("insert into tujuan_organisasi values('"+email+"','"+tujuan+"');")
                tujuanCounter+=1

            password = nama_organisasi+'123'
            pengurusCounter -=1
            for i in range(pengurusCounter):
                counter = i+1
                namaPengurus = request.POST["namaPengurusText"+str(counter)]
                emailPengurus = request.POST["emailPengurusText"+str(counter)]
                alamatPengurus = request.POST["namaPengurusText"+str(counter)]

                conn.cursor.execute("insert into sion.user values('"+emailPengurus+"','"+password+"','"+namaPengurus+"','"+alamatPengurus+"');")

                conn.cursor.execute("insert into pengurus_organisasi values('"+emailPengurus+"','"+email+"');")

                messages.info(request, "Email Pengurus "+str(counter)+" terdaftar "+emailPengurus)

            messages.info(request, "Password awal "+password)
           
            return HttpResponseRedirect(reverse('sion-login:index'))            

        return render(request, 'FormPengurusOrganisasi.html', response)

sion_register/templates/FormPengurusOrganisasi.html
<!DOCTYPE html>
<html>
<head>
	<title>Form Pengurus Organisasi</title>
	<style>
		.formInput {
			border-radius: 10%;
			height: 40px;
		}

		td, .formInput, .submit {
			font-family: Trebuchet MS;
			font-size: 30px;
		}

		.submit {
			margin: 40px;
			border-radius: 7%;
			background-color: #00cccc;
			width: 50%;
		}

		.mainContainer {
		    background: #005c99; /* For browsers that do not support gradients */
		    background: linear-gradient(#005c99,#ccebff); /* Standard syntax (must be last) */

		    background-repeat: no-repeat;
		    background-size: cover;
		    background-attachment: fixed;
		}	
	</style>
</head>
<body class = "mainContainer">
	<form method="POST" action="{% url 'sion-register:register_organisasi' %}">
	<% csrf_token %>
		<center>
		<div style="width: 1500px; background-color: #d9d9d9; margin-top: 200px;">
			<div style=" display: inline-block;">
				<h1>Organisasi</h1>
				<table id="organisasiTable">
					<tr>
						<td class="key">Nama Organisasi</td>
						<td>:</td>
						<td><input class="formInput" type="text" name="namaOrganisasiText"></td>
					</tr>
					<tr>
						<td class="key">Website</td>
						<td>:</td>
						<td><input class="formInput" type="text" name="websiteText"></td>
					</tr>
					<tr>
						<td class="key">Email</td>
						<td>:</td>
						<td><input class="formInput" type="text" name="emailText"></td>
					</tr>
					<tr>
						<td class="key">Kecamatan</td>
						<td>:</td>
						<td><input class="formInput" type="text" name="kecamatanText"></td>
					</tr>
					<tr>
						<td class="key">Kabupaten</td>
						<td>:</td>
						<td><input class="formInput" type="text" name="kabupatenText"></td>
					</tr>
					<tr>
						<td class="key">provinsi</td>
						<td>:</td>
						<td><input class="formInput" type="text" name="provinsiText"></td>
					</tr>
					<tr>
						<td class="key">Kode Pos</td>
						<td>:</td>
						<td><input class="formInput" type="text" name="kodePosText"></td>
					</tr>
					<tr>
						<td class="key">Jalan/Desa/Kelurahan/No.Rumah</td>
						<td>:</td>
						<td><input class="formInput" type="text" name="additionalAddressText"></td>
					</tr>
					<tr>
						<td style="vertical-align: text-top">Tujuan Organisasi</td>
						<td style="vertical-align: text-top">:</td>
						<td><input class="formInput" type="text" name="tujuanOrganisasiText1"></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td><button style="margin-left: 250px; border: none; background: none; font-size: 25px" type="button" onclick="tambahTujuan()">+tujuan</button></td>
					</tr>
				</table>
			</div>
			<div style=" display: inline-block;">
				<h1>Pengurus Organisasi</h1>
				
				<table id="pengurusOrganisasiTable">
					<tr>
						<td>Pengurus 1</td>
					</tr>
					<tr>
						<td class="key">Nama Pengurus</td>
						<td>:</td>
						<td><input class="formInput" type="text" name="namaPengurusText1"></td>
					</tr>
					<tr>
						<td class="key">Email Pengurus</td>
						<td>:</td>
						<td><input class="formInput" type="text" name="emailPengurusText1"></td>
					</tr>
					<tr>
						<td class="key">Alamat Pengurus</td>
						<td>:</td>
						<td><input class="formInput" type="text" name="alamatPengurusText1"></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td><button style="margin-left: 220px; border: none; background: none; font-size: 25px" type="button" onclick="tambahPengurus()">+pengurus</button></td>
					</tr>
				</table>
			</div>
			<div>
				<input class="submit" type="submit" name="submit" value="Register">
			</div>
		</div>
		</center>
	</form>

	<script>
		var tujuanCounter = 1;
		var tujuanRow = 8;

		var pengurusOrganisasiCounter = 1;
		var pengurusOrganisasiRow = 0;

		function tambahTujuan() {
			tujuanCounter++;
			tujuanRow++;

			var table = document.getElementById("organisasiTable");
			var row = table.insertRow(tujuanRow);
			var cell1 = row.insertCell(0);
			var cell2 = row.insertCell(1);
			var cell3 = row.insertCell(2);

			// Tambah input tujuan
			var newInput = document.createElement("INPUT");
			newInput.setAttribute("type", "text");
			newInput.className = "formInput";
			newInput.name = "tujuanOrganisasiText" + tujuanCounter;
			cell3.appendChild(newInput);


		}

		function tambahPengurus() {
			pengurusOrganisasiCounter++;
			pengurusOrganisasiRow += 4;

			var table = document.getElementById("pengurusOrganisasiTable")

			// Judul
			var row = table.insertRow(pengurusOrganisasiRow);
			var cell1 = row.insertCell(0);
			cell1.style.paddingTop = "20px";
			cell1.innerHTML = "Pengurus " + pengurusOrganisasiCounter;

			// Form nama
			var row = table.insertRow(pengurusOrganisasiRow+1);
			var cell1 = row.insertCell(0);
			var cell2 = row.insertCell(1);
			var cell3 = row.insertCell(2);
			cell1.className = "key";
			cell1.innerHTML = "Nama Pengurus";
			cell2.innerHTML = ":";
			var newInput = document.createElement("INPUT");
			newInput.setAttribute("type", "text");
			newInput.className = "formInput";
			newInput.name = "namaPengurusText" + pengurusOrganisasiCounter;
			cell3.appendChild(newInput);

			// Form Email
			var row = table.insertRow(pengurusOrganisasiRow+2);
			var cell1 = row.insertCell(0);
			var cell2 = row.insertCell(1);
			var cell3 = row.insertCell(2);
			cell1.className = "key";
			cell1.innerHTML = "Email Pengurus";
			cell2.innerHTML = ":";
			var newInput = document.createElement("INPUT");
			newInput.setAttribute("type", "text");
			newInput.className = "formInput";
			newInput.name = "emailPengurusText" + pengurusOrganisasiCounter;
			cell3.appendChild(newInput);

			// Form Alamat
			var row = table.insertRow(pengurusOrganisasiRow+3);
			var cell1 = row.insertCell(0);
			var cell2 = row.insertCell(1);
			var cell3 = row.insertCell(2);
			cell1.className = "key";
			cell1.innerHTML = "Alamat Pengurus";
			cell2.innerHTML = ":";
			var newInput = document.createElement("INPUT");
			newInput.setAttribute("type", "text");
			newInput.className = "formInput";
			newInput.name = "alamatPengurusText" + pengurusOrganisasiCounter;
			cell3.appendChild(newInput);
		}
	</script>
</body>
</html>

sion_register/templates/FormRegistrasiDonatur.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="https://v40.pingendo.com/assets/4.0.0/default/theme.css" type="text/css"> </head>

<body class="bg-secondary">
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">
        <i class="fa d-inline fa-lg fa-repeat"></i>
        <b>SION</b>
      </a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center justify-content-end" id="navbar2SupportedContent"> </div>
    </div>
  </nav>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12 bg-primary">
          <h1 class="display-2 text-dark text-center">Form Registrasi Donatur</h1>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <form class="">
            <div class="form-group">
              <label>Nama</label>
              <input type="email" class="form-control" placeholder="Masukkan Nama Anda"> </div>
            <div class="form-group">
              <label>Email</label>
              <input type="password" class="form-control" placeholder="Masukkan Email Anda"> </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Password</label>
              <input type="email" class="form-control" placeholder="Masukkan Password Anda"> </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Kecamatan</label>
              <input type="email" class="form-control" placeholder="Masukkan Kecamatan Anda"> </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Kabupaten</label>
              <input type="email" class="form-control" placeholder="Masukkan Ke Anda"> </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Provinsi</label>
              <input type="email" class="form-control" placeholder="Masukkan Provinsi Anda"> </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Kode Pos</label>
              <input type="email" class="form-control" placeholder="Masukkan Kode Pos Anda"> </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Jalan/Desa/Kelurahan/No.Rumah</label>
              <input type="email" class="form-control" placeholder="Masukkan Jalan/Desa/Kelurahan/No.Rumah"> </div>
            <button type="submit" class="btn btn-success btn-block">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

sion_register/templates/FormRegistrasiRelawan.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="https://v40.pingendo.com/assets/4.0.0/default/theme.css" type="text/css"> </head>

<body class="bg-secondary">
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">
        <i class="fa d-inline fa-lg fa-repeat"></i>
        <b>SION</b>
      </a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center justify-content-end" id="navbar2SupportedContent"> </div>
    </div>
  </nav>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12 bg-primary">
          <h1 class="display-2 text-dark text-center">Form Registrasi Relawan</h1>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <form class="">
            <div class="form-group">
              <label>Nama</label>
              <input type="email" class="form-control" placeholder="Masukkan Nama Anda"> </div>
            <div class="form-group">
              <label>Email</label>
              <input type="password" class="form-control" placeholder="Masukkan Email Anda"> </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Password</label>
              <input type="email" class="form-control" placeholder="Masukkan Password Anda"> </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Kecamatan</label>
              <input type="email" class="form-control" placeholder="Masukkan Kecamatan Anda"> </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Kabupaten</label>
              <input type="email" class="form-control" placeholder="Masukkan Kabupaten Anda"> </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Provinsi</label>
              <input type="email" class="form-control" placeholder="Masukkan Provinsi Anda"> </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Kode Pos</label>
              <input type="email" class="form-control" placeholder="Masukkan Kode Pos Anda"> </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Jalan/Desa/Kelurahan/No.Rumah</label>
              <input type="email" class="form-control" placeholder="Masukkan/Desa/Kelurahan/No.Rumah Anda"> </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Tanggal Lahir</label>
              <input type="email" class="form-control" placeholder="Masukkan Tanggal Lahir Anda"> </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Nomor Handphone</label>
              <input type="email" class="form-control" placeholder="Masukkan Nomor Handphone Anda"> </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Keahlaian yang Dimiliki</label>
              <input type="email" class="form-control" placeholder="Masukkan Keahlian Anda"> </div>
            <button type="submit" class="btn btn-success btn-block">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

sion_register/templates/FormRegistrasiSponsor.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="https://v40.pingendo.com/assets/4.0.0/default/theme.css" type="text/css"> </head>

<body>
  <div class="py-5 bg-secondary">
    <div class="container">
      <div class="row">
        <div class="col-md-12 bg-primary">
          <h1 class="display-2 text-dark text-center">Form Registrasi Sponsor</h1>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <form class="">
            <div class="form-group">
              <label>Nama</label>
              <input type="email" class="form-control" placeholder="Masukkan Nama Anda"> </div>
            <div class="form-group">
              <label>Email</label>
              <input type="password" class="form-control" placeholder="Masukkan Email Anda"> </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Password</label>
              <input type="email" class="form-control" placeholder="Masukkan Password Anda"> </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Kecamatan</label>
              <input type="email" class="form-control" placeholder="Masukkan Kecamatan Anda"> </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Kabupaten</label>
              <input type="email" class="form-control" placeholder="Masukkan Kecamatan Anda"> </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Provinsi</label>
              <input type="email" class="form-control" placeholder="Masukkan Provinsi Anda"> </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Kode Pos</label>
              <input type="email" class="form-control" placeholder="Masukkan Kode Pos Anda"> </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Jalan/Desa/Kelurahan/No.Rumah</label>
              <input type="email" class="form-control" placeholder="Masukkan Jalan/Desa/Kelurahan/No.Rumah"> </div>
            <div class="form-group">
              <label>Logo Sponsor</label>
              <br>
              <input type="file" name="pic" required="required" accept="image/*"> </div>
          </form>
        </div>
        <button type="submit" class="btn btn-success btn-block">Submit</button>
      </div>
    </div>
  </div>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">
        <i class="fa d-inline fa-lg fa-repeat"></i>
        <b>SION</b>
      </a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center justify-content-end" id="navbar2SupportedContent"> </div>
    </div>
  </nav>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

sion_register/templates/MilihRole.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="https://v40.pingendo.com/assets/4.0.0/default/theme.css" type="text/css"> </head>

<body class="bg-primary">
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">
        <i class="fa d-inline fa-lg fa-repeat"></i>
        <b>SION</b>
      </a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center justify-content-end" id="navbar2SupportedContent"> </div>
    </div>
  </nav>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="display-1 text-center bg-secondary text-uppercase text-dark">Register</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <i class="d-block  fa fa-5x fa-fw w-100 bg-dark fa-smile-o"></i>
          <div class="row">
            <div class="col-md-12">
              <a href="{% url 'sion-register:form_register_relawan' %}" class="btn text-center btn-block btn-success">Daftar Menjadi Relawan</a>
              <div class="row">
                <div class="col-md-12">
                  <i class="d-block  fa fa-5x fa-fw w-100 bg-dark fa-users"></i>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <a href="{% url 'sion-register:form_register_organisasi' %}" class="btn btn-block btn-success">Daftar Menjadi Pengurus Organisasi</a>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="row">
            <div class="col-md-12">
              <i class="d-block  fa fa-5x fa-fw w-100 bg-dark fa-money"></i>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <a href="{% url 'sion-register:form_register_donatur' %}" class="btn btn-block btn-success">Daftar Menjadi Donatur</a>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <i class="d-block  fa fa-5x fa-fw w-100 bg-dark fa-briefcase"></i>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <a href="{% url 'sion-register:form_register_sponsor' %}" class="btn btn-block btn-success">Daftar Menjadi Sponsor</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>